### ISSUE TITLE
Fix Compile error on Port

### ISSUE THREAD

**Issue by Karinexmachina** [first-assault-reborn/FirstAssaultReborn#47]
Dont know what this issue is about so i'll just put it here. 
![image](https://user-images.githubusercontent.com/45721251/56500723-e7d03500-6503-11e9-956e-6d052207dd8c.png)

**Comment by capnkenny** [comment]
Hey Karin, do you think you can upload a copy of the editor log after getting this to happen? And this is the `map/port branch`, correct?

(Editor log is here: C:\Users\[username]\AppData\Local\Unity\Editor\Editor.log or you click on "Open Editor Log" in the Console window)

**Comment by RubyNova** [comment]
This doesn't look like an error to do with my code but with some form of prefab data. I'll need to know what branch this occured on so I can pull it and repro.

**Comment by RubyNova** [comment]
Confirmed issue with `map/port`. @nekotashikun I'll be investigating your branch to see what's going on.

**Comment by RubyNova** [comment]
Ticket reassigned to relevant team member.

**Comment by nekotashikun** [comment]
Branch reuploaded with previously missing / deleted files by accident. Requires checking if it solves issue.

**Comment by RubyNova** [comment]
Looks fixed now. Marking as resolved.
